//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.28 at 01:19:28 PM EEST 
//


package com.siemens.ct.ro.transportation.commons;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Request.Parcel }
     * 
     */
    public Request.Parcel createRequestParcel() {
        return new Request.Parcel();
    }

    /**
     * Create an instance of {@link Request.Parcel.PredictiveModels }
     * 
     */
    public Request.Parcel.PredictiveModels createRequestParcelPredictiveModels() {
        return new Request.Parcel.PredictiveModels();
    }

    /**
     * Create an instance of {@link Request.Parcel.DeliveryTime }
     * 
     */
    public Request.Parcel.DeliveryTime createRequestParcelDeliveryTime() {
        return new Request.Parcel.DeliveryTime();
    }

    /**
     * Create an instance of {@link Request.Parcel.AcceptanceCriteria }
     * 
     */
    public Request.Parcel.AcceptanceCriteria createRequestParcelAcceptanceCriteria() {
        return new Request.Parcel.AcceptanceCriteria();
    }

    /**
     * Create an instance of {@link Request.Parcel.PredictiveModels.Candidate }
     * 
     */
    public Request.Parcel.PredictiveModels.Candidate createRequestParcelPredictiveModelsCandidate() {
        return new Request.Parcel.PredictiveModels.Candidate();
    }

}
