package com.siemens.ct.ro.transportation.commons;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.28 at 01:19:28 PM EEST 
//




import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parcel">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ids" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="receiver" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="job" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="deliveryTime">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="end" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="withTransportationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="acceptanceCriteria">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hardMinTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="hardMaxTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="hardMinHumidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="hardMaxHumidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="softMinTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="softMaxTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="maximumTimeOutOfTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="predictiveModels">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="candidate" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parcel"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlElement(required = true)
    protected Request.Parcel parcel;

    /**
     * Gets the value of the parcel property.
     * 
     * @return
     *     possible object is
     *     {@link Request.Parcel }
     *     
     */
    public Request.Parcel getParcel() {
        return parcel;
    }

    /**
     * Sets the value of the parcel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request.Parcel }
     *     
     */
    public void setParcel(Request.Parcel value) {
        this.parcel = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ids" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="receiver" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="job" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="deliveryTime">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="end" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="withTransportationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="acceptanceCriteria">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hardMinTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="hardMaxTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="hardMinHumidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="hardMaxHumidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="softMinTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="softMaxTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="maximumTimeOutOfTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="predictiveModels">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="candidate" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ids",
        "sender",
        "receiver",
        "job",
        "deliveryTime",
        "withTransportationType",
        "acceptanceCriteria",
        "predictiveModels"
    })
    public static class Parcel {

        @XmlElement(required = true)
        protected String ids;
        @XmlElement(required = true)
        protected String sender;
        @XmlElement(required = true)
        protected String receiver;
        @XmlElement(required = true)
        protected String job;
        @XmlElement(required = true)
        protected Request.Parcel.DeliveryTime deliveryTime;
        @XmlElement(required = true)
        protected String withTransportationType;
        @XmlElement(required = true)
        protected Request.Parcel.AcceptanceCriteria acceptanceCriteria;
        @XmlElement(required = true)
        protected Request.Parcel.PredictiveModels predictiveModels;

        /**
         * Gets the value of the ids property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIds() {
            return ids;
        }

        /**
         * Sets the value of the ids property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIds(String value) {
            this.ids = value;
        }

        /**
         * Gets the value of the sender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSender() {
            return sender;
        }

        /**
         * Sets the value of the sender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSender(String value) {
            this.sender = value;
        }

        /**
         * Gets the value of the receiver property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReceiver() {
            return receiver;
        }

        /**
         * Sets the value of the receiver property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReceiver(String value) {
            this.receiver = value;
        }

        /**
         * Gets the value of the job property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJob() {
            return job;
        }

        /**
         * Sets the value of the job property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJob(String value) {
            this.job = value;
        }

        /**
         * Gets the value of the deliveryTime property.
         * 
         * @return
         *     possible object is
         *     {@link Request.Parcel.DeliveryTime }
         *     
         */
        public Request.Parcel.DeliveryTime getDeliveryTime() {
            return deliveryTime;
        }

        /**
         * Sets the value of the deliveryTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.Parcel.DeliveryTime }
         *     
         */
        public void setDeliveryTime(Request.Parcel.DeliveryTime value) {
            this.deliveryTime = value;
        }

        /**
         * Gets the value of the withTransportationType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWithTransportationType() {
            return withTransportationType;
        }

        /**
         * Sets the value of the withTransportationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWithTransportationType(String value) {
            this.withTransportationType = value;
        }

        /**
         * Gets the value of the acceptanceCriteria property.
         * 
         * @return
         *     possible object is
         *     {@link Request.Parcel.AcceptanceCriteria }
         *     
         */
        public Request.Parcel.AcceptanceCriteria getAcceptanceCriteria() {
            return acceptanceCriteria;
        }

        /**
         * Sets the value of the acceptanceCriteria property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.Parcel.AcceptanceCriteria }
         *     
         */
        public void setAcceptanceCriteria(Request.Parcel.AcceptanceCriteria value) {
            this.acceptanceCriteria = value;
        }

        /**
         * Gets the value of the predictiveModels property.
         * 
         * @return
         *     possible object is
         *     {@link Request.Parcel.PredictiveModels }
         *     
         */
        public Request.Parcel.PredictiveModels getPredictiveModels() {
            return predictiveModels;
        }

        /**
         * Sets the value of the predictiveModels property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.Parcel.PredictiveModels }
         *     
         */
        public void setPredictiveModels(Request.Parcel.PredictiveModels value) {
            this.predictiveModels = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hardMinTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="hardMaxTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="hardMinHumidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="hardMaxHumidity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="softMinTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="softMaxTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="maximumTimeOutOfTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hardMinTemperature",
            "hardMaxTemperature",
            "hardMinHumidity",
            "hardMaxHumidity",
            "softMinTemperature",
            "softMaxTemperature",
            "maximumTimeOutOfTemperature"
        })
        public static class AcceptanceCriteria {

            @XmlElement(required = true)
            protected String hardMinTemperature;
            @XmlElement(required = true)
            protected String hardMaxTemperature;
            @XmlElement(required = true)
            protected String hardMinHumidity;
            @XmlElement(required = true)
            protected String hardMaxHumidity;
            @XmlElement(required = true)
            protected String softMinTemperature;
            @XmlElement(required = true)
            protected String softMaxTemperature;
            @XmlElement(required = true)
            protected String maximumTimeOutOfTemperature;

            /**
             * Gets the value of the hardMinTemperature property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHardMinTemperature() {
                return hardMinTemperature;
            }

            /**
             * Sets the value of the hardMinTemperature property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHardMinTemperature(String value) {
                this.hardMinTemperature = value;
            }

            /**
             * Gets the value of the hardMaxTemperature property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHardMaxTemperature() {
                return hardMaxTemperature;
            }

            /**
             * Sets the value of the hardMaxTemperature property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHardMaxTemperature(String value) {
                this.hardMaxTemperature = value;
            }

            /**
             * Gets the value of the hardMinHumidity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHardMinHumidity() {
                return hardMinHumidity;
            }

            /**
             * Sets the value of the hardMinHumidity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHardMinHumidity(String value) {
                this.hardMinHumidity = value;
            }

            /**
             * Gets the value of the hardMaxHumidity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHardMaxHumidity() {
                return hardMaxHumidity;
            }

            /**
             * Sets the value of the hardMaxHumidity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHardMaxHumidity(String value) {
                this.hardMaxHumidity = value;
            }

            /**
             * Gets the value of the softMinTemperature property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSoftMinTemperature() {
                return softMinTemperature;
            }

            /**
             * Sets the value of the softMinTemperature property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSoftMinTemperature(String value) {
                this.softMinTemperature = value;
            }

            /**
             * Gets the value of the softMaxTemperature property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSoftMaxTemperature() {
                return softMaxTemperature;
            }

            /**
             * Sets the value of the softMaxTemperature property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSoftMaxTemperature(String value) {
                this.softMaxTemperature = value;
            }

            /**
             * Gets the value of the maximumTimeOutOfTemperature property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaximumTimeOutOfTemperature() {
                return maximumTimeOutOfTemperature;
            }

            /**
             * Sets the value of the maximumTimeOutOfTemperature property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaximumTimeOutOfTemperature(String value) {
                this.maximumTimeOutOfTemperature = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="end" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "start",
            "end"
        })
        public static class DeliveryTime {

            @XmlElement(required = true)
            protected String start;
            @XmlElement(required = true)
            protected String end;

            /**
             * Gets the value of the start property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStart() {
                return start;
            }

            /**
             * Sets the value of the start property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStart(String value) {
                this.start = value;
            }

            /**
             * Gets the value of the end property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEnd() {
                return end;
            }

            /**
             * Sets the value of the end property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEnd(String value) {
                this.end = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="candidate" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "candidate"
        })
        public static class PredictiveModels {

            protected List<Request.Parcel.PredictiveModels.Candidate> candidate;

            /**
             * Gets the value of the candidate property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the candidate property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCandidate().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Request.Parcel.PredictiveModels.Candidate }
             * 
             * 
             */
            public List<Request.Parcel.PredictiveModels.Candidate> getCandidate() {
                if (candidate == null) {
                    candidate = new ArrayList<Request.Parcel.PredictiveModels.Candidate>();
                }
                return this.candidate;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id"
            })
            public static class Candidate {

                protected float id;

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public float getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setId(float value) {
                    this.id = value;
                }

            }

        }

    }

}
