package com.siemens.ct.ro.transportation.dao;

import com.softwareag.transportation.CEPevents.TemperaturePredictionTenMinutesValidationWithACUnitFilteringEvent;

public interface TemperaturePredictionTenMinutesValidationWithACUnitFilteringEventDao {
	public TemperaturePredictionTenMinutesValidationWithACUnitFilteringEvent add(
			TemperaturePredictionTenMinutesValidationWithACUnitFilteringEvent temperaturePredictionTenMinutesValidationWithACUnitFilteringEvent);

}
