//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.07 at 03:39:28 PM FET 
//


package com.siemens.ct.ro.transportation.dataformatfromcep;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://namespaces.softwareag.com/EDA/Event}HeaderType"/>
 *         &lt;element name="Body" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://namespaces.softwareag.com/EDA/Event}Payload"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "Event", namespace = "http://namespaces.softwareag.com/EDA/Event")
public class Event {

    @XmlElement(name = "Header", namespace = "http://namespaces.softwareag.com/EDA/Event", required = true)
    protected HeaderType header;
    @XmlElement(name = "Body", namespace = "http://namespaces.softwareag.com/EDA/Event")
    protected Event.Body body;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link Event.Body }
     *     
     */
    public Event.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link Event.Body }
     *     
     */
    public void setBody(Event.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://namespaces.softwareag.com/EDA/Event}Payload"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "payload"
    })
    public static class Body {

        @XmlElementRef(name = "Payload", namespace = "http://namespaces.softwareag.com/EDA/Event", type = JAXBElement.class)
        protected JAXBElement<?> payload;

        /**
         * Gets the value of the payload property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link S05HVACActuatorStatusType }{@code >}
         *     {@link JAXBElement }{@code <}{@link CEPGPSToVectorLengthType }{@code >}
         *     {@link JAXBElement }{@code <}{@link AggregateTemperatureType }{@code >}
         *     {@link JAXBElement }{@code <}{@link OutputEventGeneratorType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S02TruckPositionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S04TemperaturePackageType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S03TruckPackageType }{@code >}
         *     {@link JAXBElement }{@code <}{@link QueryOutputType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S01TemperatureType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S03CurrentClampType }{@code >}
         *     {@link JAXBElement }{@code <}{@link TruckSensorJoinedType }{@code >}
         *     {@link JAXBElement }{@code <}{@link Object }{@code >}
         *     {@link JAXBElement }{@code <}{@link TruckSensorJoinDocType }{@code >}
         *     {@link JAXBElement }{@code <}{@link CEPTemperatureGPSType }{@code >}
         *     {@link JAXBElement }{@code <}{@link TemperatureLowRangeWarningType }{@code >}
         *     {@link JAXBElement }{@code <}{@link Q05TruckPackageTemperatureType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S02HumidityType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S04CO2Type }{@code >}
         *     {@link JAXBElement }{@code <}{@link TemperaturePredictionType }{@code >}
         *     
         */
        public JAXBElement<?> getPayload() {
            return payload;
        }

        /**
         * Sets the value of the payload property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link S05HVACActuatorStatusType }{@code >}
         *     {@link JAXBElement }{@code <}{@link CEPGPSToVectorLengthType }{@code >}
         *     {@link JAXBElement }{@code <}{@link AggregateTemperatureType }{@code >}
         *     {@link JAXBElement }{@code <}{@link OutputEventGeneratorType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S02TruckPositionType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S04TemperaturePackageType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S03TruckPackageType }{@code >}
         *     {@link JAXBElement }{@code <}{@link QueryOutputType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S01TemperatureType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S03CurrentClampType }{@code >}
         *     {@link JAXBElement }{@code <}{@link TruckSensorJoinedType }{@code >}
         *     {@link JAXBElement }{@code <}{@link Object }{@code >}
         *     {@link JAXBElement }{@code <}{@link TruckSensorJoinDocType }{@code >}
         *     {@link JAXBElement }{@code <}{@link CEPTemperatureGPSType }{@code >}
         *     {@link JAXBElement }{@code <}{@link TemperatureLowRangeWarningType }{@code >}
         *     {@link JAXBElement }{@code <}{@link Q05TruckPackageTemperatureType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S02HumidityType }{@code >}
         *     {@link JAXBElement }{@code <}{@link S04CO2Type }{@code >}
         *     {@link JAXBElement }{@code <}{@link TemperaturePredictionType }{@code >}
         *     
         */
        public void setPayload(JAXBElement<?> value) {
            this.payload = value;
        }

    }

}
