//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.17 at 11:25:19 AM FET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://namespaces.softwareag.com/EDA/SmartBusiness", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.siemens.ct.ro.transportation.dataformatfromcep;
