//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.07 at 03:39:28 PM FET 
//


package com.siemens.ct.ro.transportation.dataformatfromcep;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryOutputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timestamp_" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="temperature" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="temperature_range" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="temperature_change" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="calibrated" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Range_alarm" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Change_alarm" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="driver_versio" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="request_i" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="temperature_sensor_i" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryOutputType", propOrder = {
    "timestamp",
    "temperature",
    "temperatureRange",
    "temperatureChange",
    "calibrated",
    "rangeAlarm",
    "changeAlarm",
    "driverVersio",
    "requestI",
    "temperatureSensorI"
})
public class QueryOutputType {

    @XmlElement(name = "timestamp_")
    protected long timestamp;
    @XmlElement(required = true)
    protected BigDecimal temperature;
    @XmlElement(name = "temperature_range", required = true)
    protected BigInteger temperatureRange;
    @XmlElement(name = "temperature_change", required = true)
    protected BigInteger temperatureChange;
    @XmlElement(required = true)
    protected BigInteger calibrated;
    @XmlElement(name = "Range_alarm", required = true)
    protected BigInteger rangeAlarm;
    @XmlElement(name = "Change_alarm", required = true)
    protected BigInteger changeAlarm;
    @XmlElement(name = "driver_versio")
    protected BigInteger driverVersio;
    @XmlElement(name = "request_i")
    protected BigInteger requestI;
    @XmlElement(name = "temperature_sensor_i")
    protected String temperatureSensorI;

    /**
     * Gets the value of the timestamp property.
     * 
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     */
    public void setTimestamp(long value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemperature(BigDecimal value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the temperatureRange property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTemperatureRange() {
        return temperatureRange;
    }

    /**
     * Sets the value of the temperatureRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTemperatureRange(BigInteger value) {
        this.temperatureRange = value;
    }

    /**
     * Gets the value of the temperatureChange property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTemperatureChange() {
        return temperatureChange;
    }

    /**
     * Sets the value of the temperatureChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTemperatureChange(BigInteger value) {
        this.temperatureChange = value;
    }

    /**
     * Gets the value of the calibrated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCalibrated() {
        return calibrated;
    }

    /**
     * Sets the value of the calibrated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCalibrated(BigInteger value) {
        this.calibrated = value;
    }

    /**
     * Gets the value of the rangeAlarm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRangeAlarm() {
        return rangeAlarm;
    }

    /**
     * Sets the value of the rangeAlarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRangeAlarm(BigInteger value) {
        this.rangeAlarm = value;
    }

    /**
     * Gets the value of the changeAlarm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChangeAlarm() {
        return changeAlarm;
    }

    /**
     * Sets the value of the changeAlarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChangeAlarm(BigInteger value) {
        this.changeAlarm = value;
    }

    /**
     * Gets the value of the driverVersio property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDriverVersio() {
        return driverVersio;
    }

    /**
     * Sets the value of the driverVersio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDriverVersio(BigInteger value) {
        this.driverVersio = value;
    }

    /**
     * Gets the value of the requestI property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequestI() {
        return requestI;
    }

    /**
     * Sets the value of the requestI property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequestI(BigInteger value) {
        this.requestI = value;
    }

    /**
     * Gets the value of the temperatureSensorI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatureSensorI() {
        return temperatureSensorI;
    }

    /**
     * Sets the value of the temperatureSensorI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatureSensorI(String value) {
        this.temperatureSensorI = value;
    }

}
