//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.07 at 03:39:28 PM FET 
//


package com.siemens.ct.ro.transportation.dataformatfromcep;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for S02_HumidityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S02_HumidityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timestamp_" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="temperature" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="humidity_range" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="humidity_change" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="temperature_valid" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="calibrated" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Range_alarm" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Change_alarm" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *       &lt;attribute name="humidity_sensor_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gateway_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S02_HumidityType", namespace = "http://namespaces.softwareag.com/SmartBusiness", propOrder = {
    "timestamp",
    "humidity",
    "temperature",
    "humidityRange",
    "humidityChange",
    "temperatureValid",
    "calibrated",
    "rangeAlarm",
    "changeAlarm"
})
public class S02HumidityType {

    @XmlElement(name = "timestamp_", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    protected double humidity;
    protected double temperature;
    @XmlElement(name = "humidity_range", required = true)
    protected BigInteger humidityRange;
    @XmlElement(name = "humidity_change", required = true)
    protected BigInteger humidityChange;
    @XmlElement(name = "temperature_valid", required = true)
    protected BigInteger temperatureValid;
    @XmlElement(required = true)
    protected BigInteger calibrated;
    @XmlElement(name = "Range_alarm", required = true)
    protected BigInteger rangeAlarm;
    @XmlElement(name = "Change_alarm", required = true)
    protected BigInteger changeAlarm;
    @XmlAttribute(name = "humidity_sensor_id")
    protected String humiditySensorId;
    @XmlAttribute(name = "gateway_id")
    protected String gatewayId;

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the humidity property.
     * 
     */
    public double getHumidity() {
        return humidity;
    }

    /**
     * Sets the value of the humidity property.
     * 
     */
    public void setHumidity(double value) {
        this.humidity = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     */
    public double getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     */
    public void setTemperature(double value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the humidityRange property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHumidityRange() {
        return humidityRange;
    }

    /**
     * Sets the value of the humidityRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHumidityRange(BigInteger value) {
        this.humidityRange = value;
    }

    /**
     * Gets the value of the humidityChange property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHumidityChange() {
        return humidityChange;
    }

    /**
     * Sets the value of the humidityChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHumidityChange(BigInteger value) {
        this.humidityChange = value;
    }

    /**
     * Gets the value of the temperatureValid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTemperatureValid() {
        return temperatureValid;
    }

    /**
     * Sets the value of the temperatureValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTemperatureValid(BigInteger value) {
        this.temperatureValid = value;
    }

    /**
     * Gets the value of the calibrated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCalibrated() {
        return calibrated;
    }

    /**
     * Sets the value of the calibrated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCalibrated(BigInteger value) {
        this.calibrated = value;
    }

    /**
     * Gets the value of the rangeAlarm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRangeAlarm() {
        return rangeAlarm;
    }

    /**
     * Sets the value of the rangeAlarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRangeAlarm(BigInteger value) {
        this.rangeAlarm = value;
    }

    /**
     * Gets the value of the changeAlarm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChangeAlarm() {
        return changeAlarm;
    }

    /**
     * Sets the value of the changeAlarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChangeAlarm(BigInteger value) {
        this.changeAlarm = value;
    }

    /**
     * Gets the value of the humiditySensorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHumiditySensorId() {
        return humiditySensorId;
    }

    /**
     * Sets the value of the humiditySensorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHumiditySensorId(String value) {
        this.humiditySensorId = value;
    }

    /**
     * Gets the value of the gatewayId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatewayId() {
        return gatewayId;
    }

    /**
     * Sets the value of the gatewayId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatewayId(String value) {
        this.gatewayId = value;
    }

}
