//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.06 at 01:11:08 PM FET 
//


package com.siemens.ct.ro.transportation.dataformatfromcep;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for S04_CO2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S04_CO2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timestamp_" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="co2" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="co2_range" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="co2_change" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Range_alarm" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Change_alarm" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="temperature" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *       &lt;attribute name="c02_sensor_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gateway_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S04_CO2Type", namespace = "http://namespaces.softwareag.com/SmartBusiness", propOrder = {
    "timestamp",
    "co2",
    "co2Range",
    "co2Change",
    "rangeAlarm",
    "changeAlarm",
    "humidity",
    "temperature"
})
public class S04CO2Type {

    @XmlElement(name = "timestamp_", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(required = true)
    protected BigDecimal co2;
    @XmlElement(name = "co2_range", required = true)
    protected BigInteger co2Range;
    @XmlElement(name = "co2_change", required = true)
    protected BigInteger co2Change;
    @XmlElement(name = "Range_alarm", required = true)
    protected BigInteger rangeAlarm;
    @XmlElement(name = "Change_alarm", required = true)
    protected BigInteger changeAlarm;
    @XmlElement(required = true)
    protected BigDecimal humidity;
    @XmlElement(required = true)
    protected BigDecimal temperature;
    @XmlAttribute(name = "c02_sensor_id")
    protected String c02SensorId;
    @XmlAttribute(name = "gateway_id")
    protected String gatewayId;

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the co2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCo2() {
        return co2;
    }

    /**
     * Sets the value of the co2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCo2(BigDecimal value) {
        this.co2 = value;
    }

    /**
     * Gets the value of the co2Range property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCo2Range() {
        return co2Range;
    }

    /**
     * Sets the value of the co2Range property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCo2Range(BigInteger value) {
        this.co2Range = value;
    }

    /**
     * Gets the value of the co2Change property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCo2Change() {
        return co2Change;
    }

    /**
     * Sets the value of the co2Change property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCo2Change(BigInteger value) {
        this.co2Change = value;
    }

    /**
     * Gets the value of the rangeAlarm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRangeAlarm() {
        return rangeAlarm;
    }

    /**
     * Sets the value of the rangeAlarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRangeAlarm(BigInteger value) {
        this.rangeAlarm = value;
    }

    /**
     * Gets the value of the changeAlarm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChangeAlarm() {
        return changeAlarm;
    }

    /**
     * Sets the value of the changeAlarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChangeAlarm(BigInteger value) {
        this.changeAlarm = value;
    }

    /**
     * Gets the value of the humidity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHumidity() {
        return humidity;
    }

    /**
     * Sets the value of the humidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHumidity(BigDecimal value) {
        this.humidity = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemperature(BigDecimal value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the c02SensorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC02SensorId() {
        return c02SensorId;
    }

    /**
     * Sets the value of the c02SensorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC02SensorId(String value) {
        this.c02SensorId = value;
    }

    /**
     * Gets the value of the gatewayId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatewayId() {
        return gatewayId;
    }

    /**
     * Sets the value of the gatewayId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatewayId(String value) {
        this.gatewayId = value;
    }

}
