//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.06 at 01:11:08 PM FET 
//


package com.siemens.ct.ro.transportation.dataformatfromcep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for S06_HVACActuatorStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S06_HVACActuatorStatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="minAllowed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxAllowed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="targetValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="hvacActuatorID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S06_HVACActuatorStatusType", namespace = "http://namespaces.softwareag.com/SmartBusiness", propOrder = {
    "active",
    "condition",
    "minAllowed",
    "maxAllowed",
    "resolution",
    "targetValue"
})
public class S06HVACActuatorStatusType {

    protected boolean active;
    @XmlElement(required = true)
    protected String condition;
    protected int minAllowed;
    protected int maxAllowed;
    protected int resolution;
    protected int targetValue;
    @XmlAttribute(name = "hvacActuatorID")
    protected String hvacActuatorID;

    /**
     * Gets the value of the active property.
     * 
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the minAllowed property.
     * 
     */
    public int getMinAllowed() {
        return minAllowed;
    }

    /**
     * Sets the value of the minAllowed property.
     * 
     */
    public void setMinAllowed(int value) {
        this.minAllowed = value;
    }

    /**
     * Gets the value of the maxAllowed property.
     * 
     */
    public int getMaxAllowed() {
        return maxAllowed;
    }

    /**
     * Sets the value of the maxAllowed property.
     * 
     */
    public void setMaxAllowed(int value) {
        this.maxAllowed = value;
    }

    /**
     * Gets the value of the resolution property.
     * 
     */
    public int getResolution() {
        return resolution;
    }

    /**
     * Sets the value of the resolution property.
     * 
     */
    public void setResolution(int value) {
        this.resolution = value;
    }

    /**
     * Gets the value of the targetValue property.
     * 
     */
    public int getTargetValue() {
        return targetValue;
    }

    /**
     * Sets the value of the targetValue property.
     * 
     */
    public void setTargetValue(int value) {
        this.targetValue = value;
    }

    /**
     * Gets the value of the hvacActuatorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHvacActuatorID() {
        return hvacActuatorID;
    }

    /**
     * Sets the value of the hvacActuatorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHvacActuatorID(String value) {
        this.hvacActuatorID = value;
    }

}
