//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.17 at 11:25:19 AM FET 
//


package com.siemens.ct.ro.transportation.dataformatfromcep;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SAGKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SAGKindType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Event"/>
 *     &lt;enumeration value="Heartbeat"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SAGKindType", namespace = "http://namespaces.softwareag.com/EDA/Event")
@XmlEnum
public enum SAGKindType {

    @XmlEnumValue("Event")
    EVENT("Event"),
    @XmlEnumValue("Heartbeat")
    HEARTBEAT("Heartbeat");
    private final String value;

    SAGKindType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SAGKindType fromValue(String v) {
        for (SAGKindType c: SAGKindType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
