//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.06.06 at 01:11:08 PM FET
//


package com.siemens.ct.ro.transportation.dataformatfromcep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for TemperaturePredictionType complex type.
*
* <p>The following schema fragment specifies the expected content contained within this class.
*
* <pre>
* &lt;complexType name="TemperaturePredictionType">
* &lt;complexContent>
* &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
* &lt;sequence>
* &lt;element name="gateway_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
* &lt;element name="temperature_sensor_id_containerTemp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
* &lt;element name="Pedicted_temp_ten_min" type="{http://www.w3.org/2001/XMLSchema}string"/>
* &lt;element name="Predicted_temp_one_hour" type="{http://www.w3.org/2001/XMLSchema}string"/>
* &lt;element name="Predicted_temp_two_hours" type="{http://www.w3.org/2001/XMLSchema}string"/>
* &lt;/sequence>
* &lt;/restriction>
* &lt;/complexContent>
* &lt;/complexType>
* </pre>
*
*
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemperaturePredictionType", propOrder = {
    "gatewayId",
    "temperatureSensorIdContainerTemp",
    "pedictedTempTenMin",
    "predictedTempOneHour",
    "predictedTempTwoHours"
})
public class TemperaturePredictionType {

    @XmlElement(name = "gateway_id")
    protected String gatewayId;
    @XmlElement(name = "temperature_sensor_id_containerTemp")
    protected String temperatureSensorIdContainerTemp;
    @XmlElement(name = "Pedicted_temp_ten_min", required = true)
    protected String pedictedTempTenMin;
    @XmlElement(name = "Predicted_temp_one_hour", required = true)
    protected String predictedTempOneHour;
    @XmlElement(name = "Predicted_temp_two_hours", required = true)
    protected String predictedTempTwoHours;
	private String sensorID;

    /**
* Gets the value of the gatewayId property.
*
* @return
* possible object is
* {@link String }
*
*/
    public String getGatewayId() {
        return gatewayId;
    }

    /**
* Sets the value of the gatewayId property.
*
* @param value
* allowed object is
* {@link String }
*
*/
    public void setGatewayId(String value) {
        this.gatewayId = value;
    }

    /**
* Gets the value of the temperatureSensorIdContainerTemp property.
*
* @return
* possible object is
* {@link String }
*
*/
    public String getTemperatureSensorIdContainerTemp() {
        return temperatureSensorIdContainerTemp;
    }

    /**
* Sets the value of the temperatureSensorIdContainerTemp property.
*
* @param value
* allowed object is
* {@link String }
*
*/
    public void setTemperatureSensorIdContainerTemp(String value) {
        this.temperatureSensorIdContainerTemp = value;
    }

    /**
* Gets the value of the pedictedTempTenMin property.
*
* @return
* possible object is
* {@link String }
*
*/
    public String getPedictedTempTenMin() {
        return pedictedTempTenMin;
    }

    /**
* Sets the value of the pedictedTempTenMin property.
*
* @param value
* allowed object is
* {@link String }
*
*/
    public void setPedictedTempTenMin(String value) {
        this.pedictedTempTenMin = value;
    }

    /**
* Gets the value of the predictedTempOneHour property.
*
* @return
* possible object is
* {@link String }
*
*/
    public String getPredictedTempOneHour() {
        return predictedTempOneHour;
    }

    /**
* Sets the value of the predictedTempOneHour property.
*
* @param value
* allowed object is
* {@link String }
*
*/
    public void setPredictedTempOneHour(String value) {
        this.predictedTempOneHour = value;
    }

    /**
* Gets the value of the predictedTempTwoHours property.
*
* @return
* possible object is
* {@link String }
*
*/
    public String getPredictedTempTwoHours() {
        return predictedTempTwoHours;
    }

    /**
* Sets the value of the predictedTempTwoHours property.
*
* @param value
* allowed object is
* {@link String }
*
*/
    public void setPredictedTempTwoHours(String value) {
        this.predictedTempTwoHours = value;
    }

	public void setSensorID(String sensorID) {
		this.sensorID = sensorID;
	}
	
	public String getSensorID()
	{
		return sensorID;
	}

}