//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.07 at 03:39:28 PM FET 
//


package com.siemens.ct.ro.transportation.dataformatfromcep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TruckSensorJoinDocType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TruckSensorJoinDocType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UDF_sensorToDoc_gateway_id_temperature_temperature_sensor_id_humidity_temperature_humidity_sensor_id_temperature_temperature_sensor_id_value_sensor_id_temperature_temperature_sensor_id" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TruckSensorJoinDocType", propOrder = {
    "udfSensorToDocGatewayIdTemperatureTemperatureSensorIdHumidityTemperatureHumiditySensorIdTemperatureTemperatureSensorIdValueSensorIdTemperatureTemperatureSensorId"
})
public class TruckSensorJoinDocType {

    @XmlElement(name = "UDF_sensorToDoc_gateway_id_temperature_temperature_sensor_id_humidity_temperature_humidity_sensor_id_temperature_temperature_sensor_id_value_sensor_id_temperature_temperature_sensor_id")
    protected Object udfSensorToDocGatewayIdTemperatureTemperatureSensorIdHumidityTemperatureHumiditySensorIdTemperatureTemperatureSensorIdValueSensorIdTemperatureTemperatureSensorId;

    /**
     * Gets the value of the udfSensorToDocGatewayIdTemperatureTemperatureSensorIdHumidityTemperatureHumiditySensorIdTemperatureTemperatureSensorIdValueSensorIdTemperatureTemperatureSensorId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUDFSensorToDocGatewayIdTemperatureTemperatureSensorIdHumidityTemperatureHumiditySensorIdTemperatureTemperatureSensorIdValueSensorIdTemperatureTemperatureSensorId() {
        return udfSensorToDocGatewayIdTemperatureTemperatureSensorIdHumidityTemperatureHumiditySensorIdTemperatureTemperatureSensorIdValueSensorIdTemperatureTemperatureSensorId;
    }

    /**
     * Sets the value of the udfSensorToDocGatewayIdTemperatureTemperatureSensorIdHumidityTemperatureHumiditySensorIdTemperatureTemperatureSensorIdValueSensorIdTemperatureTemperatureSensorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUDFSensorToDocGatewayIdTemperatureTemperatureSensorIdHumidityTemperatureHumiditySensorIdTemperatureTemperatureSensorIdValueSensorIdTemperatureTemperatureSensorId(Object value) {
        this.udfSensorToDocGatewayIdTemperatureTemperatureSensorIdHumidityTemperatureHumiditySensorIdTemperatureTemperatureSensorIdValueSensorIdTemperatureTemperatureSensorId = value;
    }

}
