//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.06 at 01:11:08 PM FET 
//


package com.siemens.ct.ro.transportation.dataformatfromcep;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TruckSensorJoinedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TruckSensorJoinedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gateway_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="temperature_containerTemp" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="temperature_sensor_id_containerTemp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="temperature_800000201" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="humidity_sensor_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="temperature_parcelTemp" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="temperature_sensor_id_parcelTemp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="value_800000301" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="sensor_id_800000301" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="temperature__800000401" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="temperature_sensor_id_800000401" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TruckSensorJoinedType", propOrder = {
    "gatewayId",
    "temperatureContainerTemp",
    "temperatureSensorIdContainerTemp",
    "humidity",
    "temperature800000201",
    "humiditySensorId",
    "temperatureParcelTemp",
    "temperatureSensorIdParcelTemp",
    "value800000301",
    "sensorId800000301",
    "temperature800000401",
    "temperatureSensorId800000401"
})
public class TruckSensorJoinedType {

    @XmlElement(name = "gateway_id")
    protected String gatewayId;
    @XmlElement(name = "temperature_containerTemp", required = true)
    protected BigDecimal temperatureContainerTemp;
    @XmlElement(name = "temperature_sensor_id_containerTemp")
    protected String temperatureSensorIdContainerTemp;
    @XmlElement(required = true)
    protected BigDecimal humidity;
    @XmlElement(name = "temperature_800000201", required = true)
    protected BigDecimal temperature800000201;
    @XmlElement(name = "humidity_sensor_id")
    protected String humiditySensorId;
    @XmlElement(name = "temperature_parcelTemp", required = true)
    protected BigDecimal temperatureParcelTemp;
    @XmlElement(name = "temperature_sensor_id_parcelTemp")
    protected String temperatureSensorIdParcelTemp;
    @XmlElement(name = "value_800000301")
    protected double value800000301;
    @XmlElement(name = "sensor_id_800000301")
    protected String sensorId800000301;
    @XmlElement(name = "temperature__800000401", required = true)
    protected BigDecimal temperature800000401;
    @XmlElement(name = "temperature_sensor_id_800000401")
    protected String temperatureSensorId800000401;

    /**
     * Gets the value of the gatewayId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatewayId() {
        return gatewayId;
    }

    /**
     * Sets the value of the gatewayId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatewayId(String value) {
        this.gatewayId = value;
    }

    /**
     * Gets the value of the temperatureContainerTemp property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemperatureContainerTemp() {
        return temperatureContainerTemp;
    }

    /**
     * Sets the value of the temperatureContainerTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemperatureContainerTemp(BigDecimal value) {
        this.temperatureContainerTemp = value;
    }

    /**
     * Gets the value of the temperatureSensorIdContainerTemp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatureSensorIdContainerTemp() {
        return temperatureSensorIdContainerTemp;
    }

    /**
     * Sets the value of the temperatureSensorIdContainerTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatureSensorIdContainerTemp(String value) {
        this.temperatureSensorIdContainerTemp = value;
    }

    /**
     * Gets the value of the humidity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHumidity() {
        return humidity;
    }

    /**
     * Sets the value of the humidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHumidity(BigDecimal value) {
        this.humidity = value;
    }

    /**
     * Gets the value of the temperature800000201 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemperature800000201() {
        return temperature800000201;
    }

    /**
     * Sets the value of the temperature800000201 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemperature800000201(BigDecimal value) {
        this.temperature800000201 = value;
    }

    /**
     * Gets the value of the humiditySensorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHumiditySensorId() {
        return humiditySensorId;
    }

    /**
     * Sets the value of the humiditySensorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHumiditySensorId(String value) {
        this.humiditySensorId = value;
    }

    /**
     * Gets the value of the temperatureParcelTemp property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemperatureParcelTemp() {
        return temperatureParcelTemp;
    }

    /**
     * Sets the value of the temperatureParcelTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemperatureParcelTemp(BigDecimal value) {
        this.temperatureParcelTemp = value;
    }

    /**
     * Gets the value of the temperatureSensorIdParcelTemp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatureSensorIdParcelTemp() {
        return temperatureSensorIdParcelTemp;
    }

    /**
     * Sets the value of the temperatureSensorIdParcelTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatureSensorIdParcelTemp(String value) {
        this.temperatureSensorIdParcelTemp = value;
    }

    /**
     * Gets the value of the value800000301 property.
     * 
     */
    public double getValue800000301() {
        return value800000301;
    }

    /**
     * Sets the value of the value800000301 property.
     * 
     */
    public void setValue800000301(double value) {
        this.value800000301 = value;
    }

    /**
     * Gets the value of the sensorId800000301 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorId800000301() {
        return sensorId800000301;
    }

    /**
     * Sets the value of the sensorId800000301 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorId800000301(String value) {
        this.sensorId800000301 = value;
    }

    /**
     * Gets the value of the temperature800000401 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemperature800000401() {
        return temperature800000401;
    }

    /**
     * Sets the value of the temperature800000401 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemperature800000401(BigDecimal value) {
        this.temperature800000401 = value;
    }

    /**
     * Gets the value of the temperatureSensorId800000401 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatureSensorId800000401() {
        return temperatureSensorId800000401;
    }

    /**
     * Sets the value of the temperatureSensorId800000401 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatureSensorId800000401(String value) {
        this.temperatureSensorId800000401 = value;
    }

}
