//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.07 at 03:39:28 PM FET 
//


package com.siemens.ct.ro.transportation.dataformatfromcep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TruckSensorFlatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TruckSensorFlatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="container_temperature_1" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="container_temperature_2" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="container_temperature_3" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="humidity_value" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="hvacStateOn" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hvacStateValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="currentClampValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="external_temperature" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="parcel_temperature" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="timestamp_" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TruckSensorFlatType", propOrder = {
    "containerTemperature1",
    "containerTemperature2",
    "containerTemperature3",
    "humidityValue",
    "hvacStateOn",
    "hvacStateValue",
    "currentClampValue",
    "externalTemperature",
    "parcelTemperature",
    "timestamp"
})
public class TruckSensorFlatType {

    @XmlElement(name = "container_temperature_1")
    protected double containerTemperature1;
    @XmlElement(name = "container_temperature_2")
    protected double containerTemperature2;
    @XmlElement(name = "container_temperature_3")
    protected double containerTemperature3;
    @XmlElement(name = "humidity_value")
    protected double humidityValue;
    protected boolean hvacStateOn;
    protected double hvacStateValue;
    protected double currentClampValue;
    @XmlElement(name = "external_temperature")
    protected double externalTemperature;
    @XmlElement(name = "parcel_temperature")
    protected double parcelTemperature;
    @XmlElement(name = "timestamp_", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the containerTemperature1 property.
     * 
     */
    public double getContainerTemperature1() {
        return containerTemperature1;
    }

    /**
     * Sets the value of the containerTemperature1 property.
     * 
     */
    public void setContainerTemperature1(double value) {
        this.containerTemperature1 = value;
    }

    /**
     * Gets the value of the containerTemperature2 property.
     * 
     */
    public double getContainerTemperature2() {
        return containerTemperature2;
    }

    /**
     * Sets the value of the containerTemperature2 property.
     * 
     */
    public void setContainerTemperature2(double value) {
        this.containerTemperature2 = value;
    }

    /**
     * Gets the value of the containerTemperature3 property.
     * 
     */
    public double getContainerTemperature3() {
        return containerTemperature3;
    }

    /**
     * Sets the value of the containerTemperature3 property.
     * 
     */
    public void setContainerTemperature3(double value) {
        this.containerTemperature3 = value;
    }

    /**
     * Gets the value of the humidityValue property.
     * 
     */
    public double getHumidityValue() {
        return humidityValue;
    }

    /**
     * Sets the value of the humidityValue property.
     * 
     */
    public void setHumidityValue(double value) {
        this.humidityValue = value;
    }

    /**
     * Gets the value of the hvacStateOn property.
     * 
     */
    public boolean isHvacStateOn() {
        return hvacStateOn;
    }

    /**
     * Sets the value of the hvacStateOn property.
     * 
     */
    public void setHvacStateOn(boolean value) {
        this.hvacStateOn = value;
    }

    /**
     * Gets the value of the hvacStateValue property.
     * 
     */
    public double getHvacStateValue() {
        return hvacStateValue;
    }

    /**
     * Sets the value of the hvacStateValue property.
     * 
     */
    public void setHvacStateValue(double value) {
        this.hvacStateValue = value;
    }

    /**
     * Gets the value of the currentClampValue property.
     * 
     */
    public double getCurrentClampValue() {
        return currentClampValue;
    }

    /**
     * Sets the value of the currentClampValue property.
     * 
     */
    public void setCurrentClampValue(double value) {
        this.currentClampValue = value;
    }

    /**
     * Gets the value of the externalTemperature property.
     * 
     */
    public double getExternalTemperature() {
        return externalTemperature;
    }

    /**
     * Sets the value of the externalTemperature property.
     * 
     */
    public void setExternalTemperature(double value) {
        this.externalTemperature = value;
    }

    /**
     * Gets the value of the parcelTemperature property.
     * 
     */
    public double getParcelTemperature() {
        return parcelTemperature;
    }

    /**
     * Sets the value of the parcelTemperature property.
     * 
     */
    public void setParcelTemperature(double value) {
        this.parcelTemperature = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

}
